#!/usr/bin/env bash
set -e

echo -ne "Content-type: text/html\n\n"

F=$(mktemp "/tmp/csonline.XXXXXXXX")
trap "rm -f $F" EXIT

# Run CovScript
json="$(cat -)"
code="$(echo $json | /var/www/html/cgi/JSON.sh | grep -e '\["code"\]')"
stdin="$(echo $json | /var/www/html/cgi/JSON.sh | grep -e '\["stdin"\]')"

code_tag='["code"]:"'
stdin_tag='["stdin"]:"'

start="$((${#code_tag} + 1))"
end="$((${#code} - 1))"
code="$(echo $code | cut -b ${start}-${end})"

start="$((${#stdin_tag} + 1))"
end="$((${#stdin} - 1))"
stdin="$(echo $stdin | cut -b ${start}-${end})"

code="$(echo $code | base64 -d)"
echo -e "$code" > "$F"
echo -e "$stdin" | /usr/bin/cs-code-runner 2>&1 $F

